const showStringOperations = () => {
    let initialString = ' Hello, World! ';
    console.log('==========================separating string operations============================================');
    console.log(initialString);
    let substring = initialString.substring(1,4);
    console.log(substring);
    let slice = initialString.slice(1,4);
    console.log(slice);
    let split = initialString.split(",");
    console.log(split);
    console.log('==========================searching through============================================');
    let indexOfl = initialString.indexOf("l");
    console.log(indexOfl);
    let indexOflGreaterThan5 = initialString.indexOf("l",5);
    console.log(indexOflGreaterThan5);
    let indexOfZZ = initialString.indexOf("zz");
    console.log(indexOfZZ); // -1 did not found
    let lastIndexOfl = initialString.lastIndexOf("l");
    console.log(lastIndexOfl);
    console.log('==========================searching through ES6============================================');
    let startsWith = initialString.startsWith("Hell");
    console.log(startsWith);
    let endsWith = initialString.endsWith("!");
    console.log(endsWith);
    let includes = initialString.includes("rld");
    console.log(includes);
    console.log('==========================creating new string with usage of old one============================================');
    let replaced = initialString.replace(",", " to js");
    console.log(replaced);
    console.log(replaced.toUpperCase());
    console.log(replaced.toLowerCase());
    console.log(replaced.normalize());
    console.log(replaced.normalize("NFD"));
    console.log('==========================single character operations============================================');
    console.log(initialString.charAt(0));
    console.log(initialString.charAt(initialString.length-1));
    console.log(initialString.charCodeAt(0));
    let love = "\ud83d\udc99";
    console.log(love.codePointAt(0));
    console.log('==========================pad operations============================================');
    let padStart = "x".padStart(3);
    console.log(padStart);
    let padEnd = "x".padEnd(3);
    console.log(padEnd);
    padStart = "x".padStart(3,"*");
    console.log(padStart);
    padEnd = "x".padEnd(3,"-");
    console.log(padEnd);
    console.log('==========================whitespace deletion============================================');
    let deleteWhitespaces = initialString.trim();
    console.log(deleteWhitespaces);
    console.log('==========================repeat============================================');
    console.log("<>".repeat(5));
    console.log('==========================string as an array============================================');
    let arrayZeroPosition = "initialString"[0];
    let arrayLastPosition = "initialString"["initialString".length-1];
    console.log(arrayLastPosition + '\n' + arrayZeroPosition);
}

module.exports = showStringOperations;